[build]
  publish = "dist"
  command = "npm run build"

# Ensure fresh fetch of apps.json on every request
[[headers]]
  for = "/apps.json"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

# Optional: some basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
